services:
  prestashop:
    container_name: prestashop
    image: lexuv2/be_193264_weloczki3:tagname
    volumes:
      - be_193264_pdata:/var/www/html:z
    restart: unless-stopped
    networks:
      - be_193264_prestashop_network
    platform: linux/x86_64 # Only for mac M1 users :)
  web:
    image: nginx:latest
    depends_on:
      - prestashop

    # host and guest ports must be identical
    ports:
      - 19326:443
    volumes:
      - be_193264_pdata:/var/www/html:z
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
      - ./certs/:/certs:z
    networks:
      - be_193264_prestashop_network

volumes:
  be_193264_pdata:

networks:
    be_193264_prestashop_network:
