version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    platform: linux/x86_64 # Only for mac M1 users :)
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: 1 # Auto install PrestaShop
      PS_DOMAIN: localhost:8080 # Your domain
    networks:
      - prestashop_network
    platform: linux/x86_64 # Only for mac M1 users :)
networks:
    prestashop_network:
