services:
  prestashop:
    container_name: prestashop
    image: lexuv2/be_193264_weloczki3:tagname
    volumes:
      - be_193264_pdata:/var/www/html
    restart: unless-stopped
    networks:
      - be_193264_prestashop_network
      - admin-mysql_default
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 512M
      
  web:
    image: nginx:latest
    depends_on:
      - prestashop

    # host and guest ports must be identical
    ports:
      - 19326:443
    volumes:
      - be_193264_pdata:/var/www/html:ro
      - /mnt/block-storage/students/projects/students-swarm-services/BE_193264/Biznes-Elektroniczny/nginx.conf:/etc/nginx/conf.d/default.conf:z
      - /mnt/block-storage/students/projects/students-swarm-services/BE_193264/Biznes-Elektroniczny/certs/:/certs:z
    networks:
      - be_193264_prestashop_network

volumes:
  be_193264_pdata:

networks:
    be_193264_prestashop_network:
    admin-mysql_default:
      external: true
