<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtdjd6f\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtdjd6f/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAtdjd6f.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAtdjd6f\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAtdjd6f\appProdProjectContainer([
    'container.build_hash' => 'Atdjd6f',
    'container.build_id' => 'e613683b',
    'container.build_time' => 1732978895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtdjd6f');
