<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZk0u6d6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZk0u6d6/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZk0u6d6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZk0u6d6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZk0u6d6\appProdProjectContainer([
    'container.build_hash' => 'Zk0u6d6',
    'container.build_id' => 'ec730455',
    'container.build_time' => 1736804043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZk0u6d6');
