<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVi56i4y\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVi56i4y/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVi56i4y.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVi56i4y\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVi56i4y\appProdProjectContainer([
    'container.build_hash' => 'Vi56i4y',
    'container.build_id' => '43513c82',
    'container.build_time' => 1733773436,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVi56i4y');
